### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by neocotic** [phaistonian/MyExtensions#33]
Although I committed a few changes in the past I just noticed that there's actually no licensing information on this project so it's unclear if/how people can make modifications to this code.

If it is open source, it should contain an OSS license (e.g. MIT).

**Comment by phaistonian** [comment]
Hey Alasdair. 

Yes, that's something I need to fix and I shall. 

Thank you for the heads up.

**Comment by neocotic** [comment]
Just noticed this was closed but I'm still not sure what the outcome is as I don't see an OSS license attached to the source or project.

**Comment by phaistonian** [comment]
@neocotic MIT on README :)

**Comment by neocotic** [comment]
Perfect! Thank you
