### ISSUE TITLE
User rating comments no longer showing up

### ISSUE THREAD

**Issue by opus1269** [phaistonian/MyExtensions#34]
I've been using this for quite a while without issue.

Recently, new user ratings comments stop showing up. I reinstalled and now the total comment count is zero and new ones are still not showing up.

It seems like it happened around the time of the Chrome Version 48.0.2564.109 m stable update, but I am not sure.

**Comment by phaistonian** [comment]
I am afraid I am too busy to check this out at the moment.

If this won't be resolved soon enough, I will try to get on it.

**Comment by primaryobjects** [comment]
I have a fix for this https://github.com/phaistonian/MyExtensions/pull/35

The problem is that the comments response JSON from Google has some of the fields in different positions. This breaks the regex that tries to parse it. I've updated the regex to account for these different positions.

**Comment by opus1269** [comment]
Latest release fixed it. Thanks.
