### ISSUE TITLE
Extension doesn't work in my spanish chrome

### ISSUE THREAD

**Issue by OscarDeDios** [phaistonian/MyExtensions#40]
Hi.
I did a pull request last week due to solve a problem with the language. In my spanish chrome the extension doesn't work because it loads a chrome store page in spanish and the it doesn't find some literals.
Could you review the pull request and upload the new version to the store please?

Regards.
OScar.

**Comment by phaistonian** [comment]
Hello.

Sorry for the super-huge delay @OscarDeDios.

Apologies for taking this long to merge.

Should be fine now.

**Comment by OscarDeDios** [comment]
Thanks for upload the new version @phaistonian 

Regards.
